version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: docker.arvancloud.ir/postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Khodnevis
    ports:
      - "8181:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.arvancloud.ir/redis:7.0
    command: --appendonly yes
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "8184:6379"

  celery:
    build: .
    command: celery -A _base worker --loglevel=info
    volumes:
      - .:/app
    links:
      - redis

  beat:
    build: .
    command: celery -A _base beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data:
  redis_data:
